"""empty message

Revision ID: 0d41a89598b5
Revises: None
Create Date: 2016-11-05 13:12:39.537041

"""

# revision identifiers, used by Alembic.
revision = '0d41a89598b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(), nullable=True),
    sa.Column('last', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(precision=2), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('spicy_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(), nullable=True),
    sa.Column('last', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(precision=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medthod', sa.String(), nullable=True),
    sa.Column('paid_amt', sa.Float(precision=2), nullable=True),
    sa.Column('tax', sa.Float(precision=2), nullable=True),
    sa.Column('ttl_bill', sa.Float(precision=2), nullable=True),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ttl_cost', sa.Float(precision=2), nullable=True),
    sa.Column('prom_id', sa.Integer(), nullable=True),
    sa.Column('pay_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pay_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['prom_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seating.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_dish')
    op.drop_table('orders')
    op.drop_table('bill')
    op.drop_table('payment')
    op.drop_table('seating')
    op.drop_table('promotion')
    op.drop_table('employee')
    op.drop_table('dish')
    op.drop_table('customer')
    ### end Alembic commands ###
